/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8e07700f-f632-4321-802d-76980a4c518f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_t4FhS4eyg",
    "aws_user_pools_web_client_id": "30gg0p3m0lb0uhepiqg6pvjsfl",
    "oauth": {}
};


export default awsmobile;
